config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
  	resources :todo_items do
  		member do
  			patch :complete
  		end
  	end
  end

  root 'todo_lists#index'
  end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  validates :item, presence: true

  def completed?
  	!completed_at.blank?
  end

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	belongs_to :user
	has_many :todo_items
 	validates :list, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todo_lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list

	def create
		@todo_item = @todo_list.todo_items.create(item_params)

		redirect_to @todo_list
	end

	def show
		@todo_item = TodoItem.find(params[:id])
	end

	def destroy
		@todo_item = TodoItem.find(params[:id])
		if @todo_item.destroy
			flash[:success] = "Todo List item was deleted"
		else
			flash[:error] = "Todo List item could not be deleted"
		end

		redirect_to @todo_list
	end

	def complete
		@todo_item = TodoItem.find(params[:id])

		@todo_item.update_attribute(:completed_at, Time.now)

		redirect_to @todo_list, notice: "Item was completed"
	end

	private
	    def set_todo_list
	      @todo_list = TodoList.find(params[:todo_list_id])
	    end

		def item_params
			params.require(:todo_item).permit(:item)
		end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :verify_correct_user, only: [:show, :edit, :update]
  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.build
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def verify_correct_user
    if current_user != TodoList.find(params[:id]).user
      redirect_to todo_lists_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:list, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--
<% if !current_user %>
	<%= link_to "Sign Up", new_user_registration_path %> 
	<%= link_to "Sign In", new_user_session_path %>
<% else %>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% end %>
<p class="alert"><%= alert %></p>
-->

<%= render 'shared/navbar' %>
<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <header class="navbar-brand"><%= link_to "Todo List Project", todo_lists_path %></header>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">Link</a></li> -->
      	<% if !current_user %>
      		<li class="dropdown">
	          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
	         	<ul class="dropdown-menu">
	        
	            <li><%= link_to "Log In", new_user_session_path %></li>

	            <li role="separator" class="divider"></li>
	            <li><%= link_to "Sign Up", new_user_registration_path %> </li>
	          	</ul>
	        </li>
			
			
		<% else %>
			<li class="dropdown">
	          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
	         	<ul class="dropdown-menu">
	           
	         	<% TodoList.all.each do |list| %>
	         		<% if list.user == current_user %>
	         			<li> <%= link_to list.list + " (" + list.todo_items.count.to_s + ")", list %> </li>
	         		<% end %>
	         	<% end %>	

	            <li role="separator" class="divider"></li>
	            <li><%= link_to 'Create new list', new_todo_list_path %></li>

	            <li role="separator" class="divider"></li>
	            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
	          	</ul>
	        </li>
		<% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
	<%= f.text_field :item, placeholder: "New Todo" %>
	<%= f.submit 'Add Todo' %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
	<% if (todo_item.completed?) %>
		<div class="todo_item">
			<p><strike><%= todo_item.item %></strike> <br> <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} %></p>
		</div>
	<% else %>
		<div class="todo_item">
			<p><%= todo_item.item %> <br> <%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %> - <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} %></p>
		</div>
	<% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list %><br>   
    <%= f.text_field :list, size: "30x10" %>
  </div>
  <p>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "50x10" %>
  </div>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="page-header">
<h1 align="center">Editing Todo List</h1>
</div>

<body align="center"><%= render 'form' %></body>

app/views/todo_lists/index.html.erb
<div class="container">

  <div class="starter-template" align="center">
    <h1>Listing Todo Lists</h1>
    <p class="lead">
    
    <% if current_user %>
    <table class="table table-striped" width="100%">
    <thead>
      <tr>
        <th width="30%">List</th>
        <th width="30%" >Description</th>
        <% if current_user == User.first %>
        <th>User</th>
        <% end %>
        <th>Options</th>
      </tr>
    </thead>

    <tbody>
      <% @todo_lists.each do |todo_list| %>
        <% if (current_user == todo_list.user) || (current_user == User.first) %>
          <tr>
            <td><%= link_to todo_list.list, todo_list %></td>
            <td><%= todo_list.description %></td>
            <% if (current_user == User.first) %>
              <td><%= todo_list.user.email %></td>
            <% end %>
            <td><%= link_to 'Show', todo_list %> | <%= link_to 'Edit', edit_todo_list_path(todo_list) %> | <%= link_to 'Delete', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    </table>
    <%= link_to 'Add a list', new_todo_list_path %>
    <% end %>

  <p id="notice"><%= notice %></p>
  </div>
</div><!-- /.container -->

app/views/todo_lists/new.html.erb
<div class="page-header">
<h1 align="center">New Todo List</h1>
</div>
<p>
<body align="center"><%= render 'form' %></body>
</p>

app/views/todo_lists/show.html.erb
<div class="page-header" align="center">
<h1><%= @todo_list.list %></h1>
</div>
<body align="center">

<p>
	<table class="table table-striped" width="60%" align="center">
    <thead>
      <tr>
        <th width="50%">List</th>
        <th>Options</th>
      </tr>
    </thead>

    <tbody>
      <% @todo_list.todo_items.each do |todo_item| %>
         <% if !todo_item.completed? %>
          	<tr>
            	<td align="left"><%= todo_item.item %></td>
           		<td align="left"><%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %> - <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
          </tr>
          <% end %>
      <% end %>

      <% @todo_list.todo_items.each do |todo_item| %>
         <% if todo_item.completed? %>
          	<tr>
            	<td align="left"><strike><%= todo_item.item %></strike></td>
           		<td align="left"><%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
          </tr>
          <% end %>
      <% end %>
    </tbody>
    </table>
</p>

<p>
	<div id="todo_items_wrapper">
		<p>
			<div id="form">
				<%= render "todo_items/form" %>
			</div>
		</p>
	</div>
</p>

</body>

<p id="notice"><%= notice %></p>

<!--
-->